/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecom.slayer.service.base;

import com.ecom.slayer.model.Shoppingcart;
import com.ecom.slayer.service.ShoppingcartLocalService;
import com.ecom.slayer.service.persistence.ShoppingcartPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the shoppingcart local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ecom.slayer.service.impl.ShoppingcartLocalServiceImpl}.
 * </p>
 *
 * @author Ecom
 * @see com.ecom.slayer.service.impl.ShoppingcartLocalServiceImpl
 * @see com.ecom.slayer.service.ShoppingcartLocalServiceUtil
 * @generated
 */
public abstract class ShoppingcartLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ShoppingcartLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ecom.slayer.service.ShoppingcartLocalServiceUtil} to access the shoppingcart local service.
	 */

	/**
	 * Adds the shoppingcart to the database. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingcart the shoppingcart
	 * @return the shoppingcart that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Shoppingcart addShoppingcart(Shoppingcart shoppingcart)
		throws SystemException {
		shoppingcart.setNew(true);

		return shoppingcartPersistence.update(shoppingcart);
	}

	/**
	 * Creates a new shoppingcart with the primary key. Does not add the shoppingcart to the database.
	 *
	 * @param cartId the primary key for the new shoppingcart
	 * @return the new shoppingcart
	 */
	@Override
	public Shoppingcart createShoppingcart(long cartId) {
		return shoppingcartPersistence.create(cartId);
	}

	/**
	 * Deletes the shoppingcart with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param cartId the primary key of the shoppingcart
	 * @return the shoppingcart that was removed
	 * @throws PortalException if a shoppingcart with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Shoppingcart deleteShoppingcart(long cartId)
		throws PortalException, SystemException {
		return shoppingcartPersistence.remove(cartId);
	}

	/**
	 * Deletes the shoppingcart from the database. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingcart the shoppingcart
	 * @return the shoppingcart that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Shoppingcart deleteShoppingcart(Shoppingcart shoppingcart)
		throws SystemException {
		return shoppingcartPersistence.remove(shoppingcart);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Shoppingcart.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return shoppingcartPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ecom.slayer.model.impl.ShoppingcartModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return shoppingcartPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ecom.slayer.model.impl.ShoppingcartModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return shoppingcartPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return shoppingcartPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return shoppingcartPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public Shoppingcart fetchShoppingcart(long cartId)
		throws SystemException {
		return shoppingcartPersistence.fetchByPrimaryKey(cartId);
	}

	/**
	 * Returns the shoppingcart with the primary key.
	 *
	 * @param cartId the primary key of the shoppingcart
	 * @return the shoppingcart
	 * @throws PortalException if a shoppingcart with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Shoppingcart getShoppingcart(long cartId)
		throws PortalException, SystemException {
		return shoppingcartPersistence.findByPrimaryKey(cartId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return shoppingcartPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the shoppingcarts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.ecom.slayer.model.impl.ShoppingcartModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of shoppingcarts
	 * @param end the upper bound of the range of shoppingcarts (not inclusive)
	 * @return the range of shoppingcarts
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<Shoppingcart> getShoppingcarts(int start, int end)
		throws SystemException {
		return shoppingcartPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of shoppingcarts.
	 *
	 * @return the number of shoppingcarts
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getShoppingcartsCount() throws SystemException {
		return shoppingcartPersistence.countAll();
	}

	/**
	 * Updates the shoppingcart in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingcart the shoppingcart
	 * @return the shoppingcart that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Shoppingcart updateShoppingcart(Shoppingcart shoppingcart)
		throws SystemException {
		return shoppingcartPersistence.update(shoppingcart);
	}

	/**
	 * Returns the shoppingcart local service.
	 *
	 * @return the shoppingcart local service
	 */
	public com.ecom.slayer.service.ShoppingcartLocalService getShoppingcartLocalService() {
		return shoppingcartLocalService;
	}

	/**
	 * Sets the shoppingcart local service.
	 *
	 * @param shoppingcartLocalService the shoppingcart local service
	 */
	public void setShoppingcartLocalService(
		com.ecom.slayer.service.ShoppingcartLocalService shoppingcartLocalService) {
		this.shoppingcartLocalService = shoppingcartLocalService;
	}

	/**
	 * Returns the shoppingcart remote service.
	 *
	 * @return the shoppingcart remote service
	 */
	public com.ecom.slayer.service.ShoppingcartService getShoppingcartService() {
		return shoppingcartService;
	}

	/**
	 * Sets the shoppingcart remote service.
	 *
	 * @param shoppingcartService the shoppingcart remote service
	 */
	public void setShoppingcartService(
		com.ecom.slayer.service.ShoppingcartService shoppingcartService) {
		this.shoppingcartService = shoppingcartService;
	}

	/**
	 * Returns the shoppingcart persistence.
	 *
	 * @return the shoppingcart persistence
	 */
	public ShoppingcartPersistence getShoppingcartPersistence() {
		return shoppingcartPersistence;
	}

	/**
	 * Sets the shoppingcart persistence.
	 *
	 * @param shoppingcartPersistence the shoppingcart persistence
	 */
	public void setShoppingcartPersistence(
		ShoppingcartPersistence shoppingcartPersistence) {
		this.shoppingcartPersistence = shoppingcartPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.ecom.slayer.model.Shoppingcart",
			shoppingcartLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.ecom.slayer.model.Shoppingcart");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Shoppingcart.class;
	}

	protected String getModelClassName() {
		return Shoppingcart.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = shoppingcartPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.ecom.slayer.service.ShoppingcartLocalService.class)
	protected com.ecom.slayer.service.ShoppingcartLocalService shoppingcartLocalService;
	@BeanReference(type = com.ecom.slayer.service.ShoppingcartService.class)
	protected com.ecom.slayer.service.ShoppingcartService shoppingcartService;
	@BeanReference(type = ShoppingcartPersistence.class)
	protected ShoppingcartPersistence shoppingcartPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ShoppingcartLocalServiceClpInvoker _clpInvoker = new ShoppingcartLocalServiceClpInvoker();
}