/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecom.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Shoppingcart service. Represents a row in the &quot;ecom_Shoppingcart&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ecom.slayer.model.impl.ShoppingcartModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ecom.slayer.model.impl.ShoppingcartImpl}.
 * </p>
 *
 * @author Ecom
 * @see Shoppingcart
 * @see com.ecom.slayer.model.impl.ShoppingcartImpl
 * @see com.ecom.slayer.model.impl.ShoppingcartModelImpl
 * @generated
 */
public interface ShoppingcartModel extends BaseModel<Shoppingcart>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shoppingcart model instance should use the {@link Shoppingcart} interface instead.
	 */

	/**
	 * Returns the primary key of this shoppingcart.
	 *
	 * @return the primary key of this shoppingcart
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shoppingcart.
	 *
	 * @param primaryKey the primary key of this shoppingcart
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cart ID of this shoppingcart.
	 *
	 * @return the cart ID of this shoppingcart
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this shoppingcart.
	 *
	 * @param cartId the cart ID of this shoppingcart
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the group ID of this shoppingcart.
	 *
	 * @return the group ID of this shoppingcart
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this shoppingcart.
	 *
	 * @param groupId the group ID of this shoppingcart
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this shoppingcart.
	 *
	 * @return the company ID of this shoppingcart
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this shoppingcart.
	 *
	 * @param companyId the company ID of this shoppingcart
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this shoppingcart.
	 *
	 * @return the user ID of this shoppingcart
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this shoppingcart.
	 *
	 * @param userId the user ID of this shoppingcart
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this shoppingcart.
	 *
	 * @return the user uuid of this shoppingcart
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this shoppingcart.
	 *
	 * @param userUuid the user uuid of this shoppingcart
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this shoppingcart.
	 *
	 * @return the user name of this shoppingcart
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this shoppingcart.
	 *
	 * @param userName the user name of this shoppingcart
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this shoppingcart.
	 *
	 * @return the create date of this shoppingcart
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this shoppingcart.
	 *
	 * @param createDate the create date of this shoppingcart
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this shoppingcart.
	 *
	 * @return the modified date of this shoppingcart
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this shoppingcart.
	 *
	 * @param modifiedDate the modified date of this shoppingcart
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the item ID of this shoppingcart.
	 *
	 * @return the item ID of this shoppingcart
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this shoppingcart.
	 *
	 * @param itemId the item ID of this shoppingcart
	 */
	public void setItemId(long itemId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.ecom.slayer.model.Shoppingcart shoppingcart);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.ecom.slayer.model.Shoppingcart> toCacheModel();

	@Override
	public com.ecom.slayer.model.Shoppingcart toEscapedModel();

	@Override
	public com.ecom.slayer.model.Shoppingcart toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}